Repository CiscoDevNet/ansible-meraki, pull requests merged in 2020-07, with the labels that each got.

#118 Rewrite request() to be more friendly
  changelogs/fragments/sanity_fixes.yml
  plugins/module_utils/network/meraki/meraki.py
Labels: enhancement

#119 Update meraki_network to be compatible with new API
  changelogs/fragments/meraki_network_update.yml
  changelogs/fragments/requests-rewrite.yml
  plugins/modules/meraki_network.py
  tests/integration/targets/meraki_network/tasks/main.yml
Labels: documentation, enhancement

#124 meraki_firewalled_services - Update URLs for v1
  changelogs/fragments/meraki_firewalled_services.yml
  plugins/modules/meraki_firewalled_services.py
Labels: bug

#125 meraki_intrusion_prevention - Update URLs and documentation for v1
  changelogs/fragments/meraki_intrusion_prevention.yml
  plugins/modules/meraki_intrusion_prevention.py
  tests/integration/targets/meraki_intrusion_prevention/tasks/tests.yml
Labels: bug, documentation

#126 Update meraki_malware for new endpoint URLs
  changelogs/fragments/meraki_malware.yml
  plugins/modules/meraki_malware.py
Labels: bug

#129 Update switchport module for API v1
  changelogs/fragments/meraki_switchport.yml
  plugins/modules/meraki_switchport.py
  tests/integration/inventory.networking.template
  tests/integration/targets/meraki_switchport/tasks/main.yml
Labels: enhancement

#127 WIP: meraki_snmp - Update URLs for v1
  changelogs/fragments/meraki_snmp.yml
  plugins/modules/meraki_snmp.py
  tests/integration/targets/meraki_snmp/tasks/main.yml
Labels: bug, documentation

#134 meraki_webhook - Fix responses and crash in webhook
  changelogs/fragments/meraki_webhook.yml
  plugins/modules/meraki_webhook.py
  tests/integration/targets/meraki_webhook/tasks/tests.yml
Labels: bug

#135 Add changelog plugin-cache to gitignore
  .gitignore
Labels: enhancement

#136 meraki_device - Update module for API v1
  changelogs/fragments/meraki_device.yml
  plugins/modules/meraki_device.py
  tests/integration/targets/meraki_device/tasks/main.yml
Labels: enhancement

#137 meraki_vlan - Update module for API v1
  changelogs/fragments/meraki_vlan.yml
  plugins/modules/meraki_vlan.py
  tests/integration/targets/meraki_vlan/tasks/main.yml
Labels: bug

#143 meraki_mx_l7_firewall - Update endpoints for API v1
  plugins/modules/meraki_mx_l7_firewall.py
Labels: bug

#144 meraki_mx_site_to_site_firewall - Update endpoints for API v1
  changelogs/fragments/meraki_mx_l7_firewall.yml
  plugins/modules/meraki_mx_site_to_site_firewall.py
  tests/integration/targets/meraki_mx_site_to_site_firewall/tasks/main.yml
Labels: bug

#145 meraki_nat - Update endpoints for API v1
  changelogs/fragments/meraki_nat.yml
  plugins/modules/meraki_nat.py
Labels: bug

#146 meraki_static_route - Update endpoints for API v1
  changelogs/fragments/meraki_static_route.yml
  plugins/modules/meraki_static_route.py
Labels: bug

#147 meraki_ssid - Fix formatting on VLAN tags
  changelogs/fragments/ssid_tags.yml
  plugins/modules/meraki_ssid.py
Labels: bug

#150 Add build_ignore items and changelog fragment for 1.0
  changelogs/fragments/build_ignore.yml
  galaxy.yml
Labels: bug

#154 meraki_switch_stack - Update module for API v1
  changelogs/fragments/meraki_switch_stack.yml
  plugins/modules/meraki_switch_stack.py
  tests/integration/targets/meraki_switch_stack/tasks/main.yml
Labels: bug

#155 meraki_site_to_site_vpn - Update endpoints to API v1
  changelogs/fragments/meraki_site_to_site_vpn.yml
  plugins/modules/meraki_site_to_site_vpn.py
Labels: bug

#115 Adds WPA3 spec to options
  changelogs/fragments/meraki_wpa3_transition.yml
  plugins/modules/meraki_ssid.py
  tests/integration/targets/meraki_ssid/tasks/main.yml
Labels: enhancement

#156 Renamed meraki_mx_uplink to meraki_mx_uplink_bandwidth
  changelogs/fragments/meraki_mx_uplink.yml
  plugins/modules/meraki_mx_uplink.py
  plugins/modules/meraki_mx_uplink_bandwidth.py
  tests/integration/targets/meraki_mx_uplink/tasks/main.yml
Labels: enhancement

#161 meraki_ssid - Update endpoints for V1
  changelogs/fragments/meraki_ssid.yml
  plugins/modules/meraki_ssid.py
Labels: bug

#160 meraki_ssid - Add support for WPA3
  changelogs/fragments/ssid_wpa3.yml
  plugins/modules/meraki_admin.py
  plugins/modules/meraki_config_template.py
  plugins/modules/meraki_ssid.py
  tests/integration/targets/meraki_ssid/tasks/main.yml
Labels: enhancement
