Repository CiscoDevNet/ansible-meraki, pull requests merged in 2023-01, with the labels that each got.

#411 Perform checks for check mode instead of submitting
  changelogs/fragments/mx-s2s.yaml
  plugins/modules/meraki_mx_site_to_site_vpn.py
  tests/integration/targets/meraki_mx_site_to_site_vpn/tasks/main.yml
Labels: bug

#418 Remove trailing whitespace
  plugins/modules/meraki_mx_site_to_site_vpn.py
Labels: bug

#417 Add meraki_network_settings module
  changelogs/fragments/412-meraki_network-settings.yaml
  plugins/modules/meraki_network_settings.py
  tests/integration/targets/meraki_network_settings/aliases
  tests/integration/targets/meraki_network_settings/tasks/main.yml
Labels: new module

#421 Added the simple workflow for ansible-lint
  .github/workflows/ansible-lint.yml
  changelogs/fragments/workflow-ansible-lint.yml
Labels: ready to test

#420 meraki_alert - Fix some alert notifications so they don't crash
  changelogs/fragments/414-alert-emails.yaml
  plugins/modules/meraki_alert.py
  tests/integration/targets/meraki_alert/tasks/main.yml
Labels: bug, waiting_for_response
